name: objectbox1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  objectbox: ^1.6.2
  objectbox_flutter_libs: any

  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  lint: ^1.10.0
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

