// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/data/studentModel.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2870111903659295128),
      name: 'Student',
      lastPropertyId: const IdUid(6, 56801012027976605),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7600232448805421105),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 633974962303456324),
            name: 'studentName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7133917218963804015),
            name: 'age',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7666222656841120700),
            name: 'address',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8532628020516310156),
            name: 'dateOfBirth',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 56801012027976605),
            name: 'totalMarks',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2870111903659295128),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Student: EntityDefinition<Student>(
        model: _entities[0],
        toOneRelations: (Student object) => [],
        toManyRelations: (Student object) => {},
        getId: (Student object) => object.id,
        setId: (Student object, int id) {
          object.id = id;
        },
        objectToFB: (Student object, fb.Builder fbb) {
          final studentNameOffset = fbb.writeString(object.studentName);
          final addressOffset = fbb.writeString(object.address);
          fbb.startTable(7);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, studentNameOffset);
          fbb.addInt64(2, object.age);
          fbb.addOffset(3, addressOffset);
          fbb.addInt64(4, object.dateOfBirth.millisecondsSinceEpoch);
          fbb.addFloat64(5, object.totalMarks);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Student(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              studentName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              age: const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              address: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              dateOfBirth: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)),
              totalMarks: const fb.Float64Reader()
                  .vTableGet(buffer, rootOffset, 14, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Student] entity fields to define ObjectBox queries.
class Student_ {
  /// see [Student.id]
  static final id = QueryIntegerProperty<Student>(_entities[0].properties[0]);

  /// see [Student.studentName]
  static final studentName =
      QueryStringProperty<Student>(_entities[0].properties[1]);

  /// see [Student.age]
  static final age = QueryIntegerProperty<Student>(_entities[0].properties[2]);

  /// see [Student.address]
  static final address =
      QueryStringProperty<Student>(_entities[0].properties[3]);

  /// see [Student.dateOfBirth]
  static final dateOfBirth =
      QueryIntegerProperty<Student>(_entities[0].properties[4]);

  /// see [Student.totalMarks]
  static final totalMarks =
      QueryDoubleProperty<Student>(_entities[0].properties[5]);
}
